### ISSUE TITLE
项目缺少资源

### ISSUE THREAD

**Issue by xingag** [MakoFeng/WatermarkDemo#1]
缺少资源， backgroundResId = mTypedArray.getResourceId(R.styleable.watermark_backgroundResId, backgroundResId)，麻烦重现上传一次，多谢！

**Comment by MakoFeng** [comment]
WatermarkView已经没有用了，改用WatermarkDrawable了

**Comment by xingag** [comment]
多谢，可以了，建议把不需要的东西删除！
